config: !!python/object:argparse.Namespace
  batch_size: 64
  debug: 'False'
  device: cuda
  dpout_fc: 0.0
  dpout_lstm: 0.0
  embedding_dim: 300
  encoder_type: BLSTM_Encoder
  epochs: 20
  fc_dim: 512
  glove_name: 840B
  log_dir: logs/
  lr: 0.1
  lstm_num_hidden: 2048
  max_pooling: 'True'
  num_workers: 4
  progress_bar: false
  seed: 42
  vocab_size: 33635
